### ISSUE TITLE
要確認テストケース

### ISSUE THREAD

**Issue by ntk221** [molhot/minishell_expand#17]
- [x] #18
- [x] `echo "$"`
- [x] `echo hoge | |` (syntax errorで弾く？)
- [x] `echo "                                      $"`

**Comment by molhot** [comment]
cat <>
はじく予定

**Comment by molhot** [comment]
echo hoge | | (syntax errorで弾く？)
↑はじきました

**Comment by molhot** [comment]
cat $path new.txt
（$pathには何もない

**Comment by molhot** [comment]
echo < andlawjda
上記の時強制終了されていたが修正済み

**Comment by molhot** [comment]
builtinが実行されると、出入り口が整理されずに（以前の入出力が引き継がれて）出力される

**Comment by molhot** [comment]
stashfdを入れたことによって-1のものが入ってきたときにfatalerrorを引き起こした
修正済み

**Comment by molhot** [comment]
cdコマンドは引数を必ずとる実装で良い？

**Comment by molhot** [comment]
exportを行うと環境変数が勝手に取る形が望ましそう

**Comment by molhot** [comment]
export時に宣言名がなんでも通ってしまっていた、修正済み
minishell$ export 111="111"
minishell: export: `111=111': not a valid identifier

**Comment by ntk221** [comment]
done
