### ISSUE TITLE
`echo "$PATH $PATH"`

### ISSUE THREAD

**Issue by ntk221** [molhot/minishell_expand#18]

**Comment by ntk221** [comment]
<img width="702" alt="スクリーンショット 2023-02-24 8 58 04" src="https://user-images.githubusercontent.com/92190938/221058457-a6e24a35-5d5f-42cd-b09d-28843678db60.png">

expand/expand_simplecommand.c の中の関数で，インクリメントが２回されていることが原因であると判断し，修正した。

**Comment by molhot** [comment]
こちらでコード修正、解決したっぽい！

**Comment by ntk221** [comment]
done
