### ISSUE TITLE
使用禁止関数を取り除く

### ISSUE THREAD

**Issue by molhot** [molhot/minishell_expand#82]

**Comment by molhot** [comment]
多分大体行けたはず、遊びながら確認

**Comment by ntk221** [comment]
![image](https://user-images.githubusercontent.com/92190938/222484983-50d6e0e2-edd8-4d0c-b394-7073dba4e579.png)

**Comment by ntk221** [comment]
calloc , dprintf

**Comment by molhot** [comment]
おわり♡
